---
title: A-Frame
subtitle: Building Blocks for the VR Web
description: Building Blocks for the VR Web
author: MozVR
email: aframe@mozilla.com
language: null
robots: none
blog_title: Blog
theme_color: black
url: 'http://localhost:4000'
root: /
permalink: 'blog/:title/'
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
force_https: false
aframe_lib:
    prod_home_url: 'https://aframe.io'
    prod_examples_url: 'https://aframe.io/aframe/examples'
    home_url: 'http://localhost:9000'
    examples_url: 'http://localhost:9000/examples'
source_dir: src
public_dir: public
new_post_name: ':title.md'
default_layout: page
auto_spacing: false
titlecase: false
external_link: true
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
    enable: true
    line_number: false
    tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
archive: 0
category: 0
tag: 0
server:
    port: 4000
    log: true
date_format: MMM D YYYY
time_format: 'H:mm:ss'
per_page: 10
pagination_dir: page
theme: aframe
exclude_generator:
    - index
feed:
    type: rss2
    path: feed.xml
    limit: 15
    hub: null
marked:
    gfm: true
    pedantic: false
    sanitize: false
    tables: true
    breaks: false
    smartLists: true
    smartypants: true
    modifyAnchors: 1
browsersync:
    notify: false
deploy:
    type: git
    repository: 'git@github.com:aframevr/aframevr.github.io.git'
disqus_shortname: null
twitter:
    username: aframevr
    url: 'https://twitter.com/aframevr/'
google_analytics: UA-24056643-4
fb_app_id: 1535794316743373
github:
    aframe:
        username: aframevr
        repo: aframe
        url: 'https://github.com/aframevr/aframe/'
    aframe_site:
        username: aframevr
        repo: aframe-site
        url: 'https://github.com/aframevr/aframe-site/'
slack:
    aframe:
        signup_url: 'https://aframevr-slack.herokuapp.com'
aframe_version: 0.2.0
spa: false

